### PR TITLE
Make the Markdown presentations fancier when being shown

### PR DESCRIPTION
**Pull request by PhilRunninger**
There is a lot to unpack in this one. I wanted to make my presentations a bit spiffier, as if rendered to HTML. Of course, we're limited by what we can do with mono-spaced characters in a Vim buffer. So here's what I did.

### Markdown-specific Changes
1. Only `#` and `##` headings are used as slide separators now.
1. `#`, `##`, and `###` headings are replaced by the output of the program [figlet](https://figlet.org), if it's installed and `g:presenting_figlets` is `1`. The fonts for both large and small headings can be overridden by the user.
1. `#`, `##`, `###`, and `####` headings are centered in the window. This at least partially addresses #22.
1. Bullets are replaced by the Unicode bullet operator: `∙`
1. Numbered lists are autonumbered, and respect the original indentation.
1. Github-flavored Markdown's checkboxes are rendered with respective Unicode characters: `□` and `■`
1. Github-flavored Markdown's tables are rendered with box drawing characters. Some special considerations need to be observed with tables.
1. Quote blocks are word-wrapped and have a left border: `┃`
1. Code blocks are preceded and followed by a horizontal line: `━`
1. Comments can be added to slides. Lines starting with `//` will not be displayed when presenting.
1. Markdown syntax highlighting is extended to highlight the new text described above.

Here is an animated GIF showing the changes. It is also embedded in the README.

FancyMarkdown

### General Changes
1. The keys used to advance, rewind, and quit a slide show are now configurable.
1. Default slide separator regex strings are set in filetype plugin files (`ftplugin/*.vim`) as opposed to autocommands. This puts the code in a location that better matches its purpose. If additional statements are needed, they fit better in these files than in an autocommand. 
1. A standard, extendable framework is introduced in the form of the `s:Format()` function and the related `autoload/markdown.vim` file. Following the pattern set forth therein, custom formatting can be implemented for other filetypes as well. For example, to enable custom formatting for **RST** files, do the following:
    1. Write the function `rst#format(text, state)` in the new file `autoload/rst.vim`. This function takes the current line of `text` and a `state` dictionary that describes the current state of the process. `state` can be used to remember such things as "We're inside a code block," which would change how the current `text` is formatted. An updated `state` is returned by this function, and is passed back in for the next line of `text`.
    1. If custom syntax highlighting is desired, create the file `syntax/presenting_rst.vim`, and include the appropriate `syntax` and `highlight` commands in it.

### CODE REVIEW

**Comment by PhilRunninger** [comment]
@sotte , I've heard it said that software is never finished; it's just released. With that in mind, I made a few changes after creating the pull request, but I'm done now. Go ahead and merge this if you approve it.

**Comment by sotte** [comment]
Wow @PhilRunninger, this is quite the PR! Thank you and I'm glad you're enjoying the presenting.vim. Also thanks for the small commits with proper commit messages! I'll try to review it this weekend.

Can you please add some screenshots to the PR showing off the new features especially figlet.

I'm thinking of re-recording the asciicast in the README.

**Comment by PhilRunninger** [comment]
@sotte, I created an animated GIF of the new Markdown formatting. It is embedded in the README and (now) in the PR description.

**Comment by sotte** [comment]
Thank you so much. This is a really nice feature, I'm impressed!

I also like the [attention to detail](https://github.com/sotte/presenting.vim/pull/26/files#diff-52c93c7c9fdf8ba663170d684d522021R90) ;)

**Comment by sotte** [comment]
I'm trying it out now. Do you plan to add any more features to this PR or is it feature complete? @PhilRunninger

**Comment by sotte** [comment]
I don't get any of the cool new features. I think vimwiki (when using markdown) collides with presenting.vim. Debugging...

**Comment by sotte** [comment]
Yes, it was vimwiki. Without vimwiki I get the new features. But I still have some issues with figlet.


image

**Comment by PhilRunninger** [comment]
I'm done with this PR. If I think of anything else, I'll create another one.

My Mac installation of figlet includes the `figlist` command which shows all the installed figlet fonts. Alternatively you can try `figlet -I 2` to display the folder where fonts are installed. You can then specify a different font by putting, for example, `let g:presenting_font_small = 'mini'` in your `.vimrc`.

**Comment by sotte** [comment]
Hey @PhilRunninger, thanks for the quick response and the help!

Two things:

- Please add a section "Known issues" to the README and the docs and mention that presenting.vim and vimwiki are not playing well together

- Please change `straight` figlet font to something else. `straight` is not available on Ubuntu by default. We should pick a font that is available on many platforms. Here is a list of the available ones on Ubuntu.

```
Default font: standard                                                                        
Font directory: /usr/share/figlet                                                             
Figlet fonts in this directory:                                                               
banner                                                                                        
big                                                                                           
block                                                                                         
bubble                                                                                        
digital                                                                                       
ivrit                                                                                         
lean                                                                                          
mini                                                                                          
mnemonic                                                                                      
script                                                                                        
shadow                                                                                        
slant                                                                                         
small                                                                                         
smscript
smshadow
smslant
standard
term
```

After that I'll merge it.

**Comment by PhilRunninger** [comment]
@sotte I'll do you one better on that [vimwiki](https://github.com/vimwiki/vimwiki) issue. I added a simple check for the **vimwiki** filetype, and changed that back to **markdown** when preparing the slide show.

The more direct replacement for **straight** would have been **mini**, but I decided that I like the blocky fonts better, so I picked **standard** and **small** for the defaults.

**Comment by sotte** [comment]
@PhilRunninger great feature and great commits!
I'm excited to use it for my next presentation.

Thank you so much!

**Comment by PhilRunninger** [comment]
My pleasure. I'm interested to see if anyone else implements this custom formatting for the other file types.

**Comment by sotte** [comment]
Me too. I created a ticket for it: #27

**Pull request merged**
