### PR TITLE
Re-enable syntax highlighting in markdown code blocks

### LINKED ISSUE #31: Syntax HL for code blocks not working
image

Snippet of codes are wrappered around thick borders, but does not have any colour syntax support.
Anyway to use 'bat' if it's installed?

### PR DESCRIPTION
**Pull request by PhilRunninger**
Fixes #31.

1. Keep the code block delimiters if they include a language for syntax highlighting. If there is no language specified, remove the delimiters, but keep the blank line. Overall this adds two additional lines to the length of the slide, but that should be OK in most situations.
1. Use the full terminal width for proper centering of text on the screen during presentations. Before it was using the window width, which is less than ideal if you have your Markdown file in a vertically split window.
1. Update the example file to include both kinds of code blocks.
1. Update the animated GIF to show the fix.

### CODE REVIEW

**Comment by sotte** [comment]
@PhilRunninger thank you so much!

@chris542 this address your issue #31. It would be great if you can check this out as well to see if you can find any edge cases.

I'll merge it then.

**Comment by chris542** [comment]
Hey i havent been on github recently!! Just saw this. Thanks for the fix! I'll have a look at it now

**Review by chris542 — APPROVED** [review]
Nice work :)

**Comment by sotte** [comment]
:+1: @PhilRunninger

**Pull request merged**
